// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK1aM3g98sJXCVUWm0EUB0smI6TRoZIJE',
    appId: '1:943493738194:web:d05239fe3090c41dd8870b',
    messagingSenderId: '943493738194',
    projectId: 'recipe-share-65df3',
    authDomain: 'recipe-share-65df3.firebaseapp.com',
    storageBucket: 'recipe-share-65df3.appspot.com',
    measurementId: 'G-SC6WB8K3R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpkHaV_0RlTGJOzPm0CROWhaUhFEYheU',
    appId: '1:943493738194:android:755f380f0376c593d8870b',
    messagingSenderId: '943493738194',
    projectId: 'recipe-share-65df3',
    storageBucket: 'recipe-share-65df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOeMvJm77w-zUtJ7kv-T_ic2O1CY1ppM',
    appId: '1:943493738194:ios:4c7072fdc23eb6eed8870b',
    messagingSenderId: '943493738194',
    projectId: 'recipe-share-65df3',
    storageBucket: 'recipe-share-65df3.appspot.com',
    iosClientId: '943493738194-fs1accn2smthmlq8ooapgs2npkkbho9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOeMvJm77w-zUtJ7kv-T_ic2O1CY1ppM',
    appId: '1:943493738194:ios:e77e4842abc6e369d8870b',
    messagingSenderId: '943493738194',
    projectId: 'recipe-share-65df3',
    storageBucket: 'recipe-share-65df3.appspot.com',
    iosClientId: '943493738194-aee1nr1f6k0c2vq7b3b71cokh9ojvsp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeapp.RunnerTests',
  );
}
